"use client";

import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowUpLeft, CheckCheck, ChevronLeft, ChevronRight, Clock3, Expand, Flag, FolderKanban, LayoutDashboard, Pause, Play, Radio, Users, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { activeTasks, overdue, overdueDays, delayLabel, pages, taskRank, type DisplayState, type DisplayTask } from './tv-dashboard-model';
import './tv-dashboard.css';

const labels:Record<string,string>={open:'بانتظار الاستلام',progress:'قيد التنفيذ',approval:'بانتظار الاعتماد',completed:'مكتملة'};
const approvalLabels:Record<string,string>={deadline_extension:'تمديد موعد',task_close:'إغلاق مهمة',project_create:'مشروع جديد',rule:'قاعدة عمل',policy:'سياسة'};
const followupLabels:Record<string,string>={overdue_task:'متابعة مهمة متأخرة',silent_task:'طلب تحديث',stale_approval:'تذكير بموافقة',daily_digest:'ملخص الفريق',queued:'إشعار'};
type Slide={kind:'overview'|'tasks'|'team'|'decisions';title:string;page:number;total:number};
function Ring({value,size=100}:{value:number;size?:number}) {return <svg width={size} height={size} viewBox="0 0 100 100" role="img" aria-label={`نسبة الإنجاز ${value} بالمئة`}><circle className="tv-ring-track" cx="50" cy="50" r="42"/><circle className="tv-ring-value" cx="50" cy="50" r="42" strokeDasharray="263.9" strokeDashoffset={263.9*(1-value/100)}/><text x="50" y="56" textAnchor="middle">{value}%</text></svg>;}
function Empty({text='لا توجد عناصر لعرضها'}:{text?:string}) {return <div className="tv-empty"><CheckCheck/><p>{text}</p></div>;}
function Badge({task,now}:{task:DisplayTask;now:number}) {return <span className={`tv-badge ${task.blocker?'danger':overdue(task,now)?'danger':task.status}`}><i/>{overdueDays(task,now)>0?`${task.blocker?'متوقفة · ':''}${delayLabel(overdueDays(task,now))}`:task.blocker?'متوقفة':labels[task.status]||task.status}</span>;}
export function TVDashboard({data,lastUpdated,onExit,preview=false}:{data:DisplayState;lastUpdated:number;onExit:()=>void;preview?:boolean}) {
  const [now,setNow]=useState(()=>Date.now());const [index,setIndex]=useState(0);const [paused,setPaused]=useState(false);const [elapsed,setElapsed]=useState(0);const [seconds,setSeconds]=useState(20);const [notice,setNotice]=useState('');const [reduced,setReduced]=useState(false);
  useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{setReduced(media.matches);if(media.matches)setPaused(true);};sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
  useEffect(()=>{
    if(paused||reduced)return;
    let frame=0,last=0,position=window.scrollY,holdUntil=performance.now()+3500;
    const suspend=()=>{holdUntil=performance.now()+10000;};
    const step=(time:number)=>{
      const delta=last?Math.min(time-last,50):0;last=time;if(time<holdUntil)position=window.scrollY;
      if(!document.hidden&&time>=holdUntil){
        const end=document.documentElement.scrollHeight-window.innerHeight;
        if(end>2){
          if(window.scrollY>=end-2){window.scrollTo({top:0,behavior:'instant'});position=0;holdUntil=time+3500;}
          else {position+=delta*0.025;window.scrollTo({top:position,behavior:'instant'});}
        }
      }
      frame=requestAnimationFrame(step);
    };
    frame=requestAnimationFrame(step);window.addEventListener('wheel',suspend,{passive:true});window.addEventListener('touchstart',suspend,{passive:true});
    return()=>{cancelAnimationFrame(frame);window.removeEventListener('wheel',suspend);window.removeEventListener('touchstart',suspend);};
  },[paused,reduced]);
  const tasks=useMemo(()=>activeTasks(data),[data]);
  const projects=data.projects.filter(p=>!p.archivedAt&&p.status!=='archived'&&p.status!=='rejected');
  const sorted=[...tasks].sort((a,b)=>taskRank(a,now)-taskRank(b,now)||a.title.localeCompare(b.title,'ar'));
  const projectPages=pages(projects,4);const taskPages=[sorted.filter(task=>task.status!=="completed")];const teamPages=pages(data.users.filter(u=>u.active),6);
  const pending=data.monitoring?.approvals.filter(a=>a.status==='pending')||[];
  const decisions=[...pending.map(a=>({id:'a'+a.id,title:a.summary,person:a.requestedByName,label:approvalLabels[a.type]||'طلب موافقة'})),...tasks.filter(t=>t.status==='approval').map(t=>({id:'t'+t.id,title:t.title,person:t.owner||'غير مسندة',label:'اعتماد إنجاز'}))];
  const decisionPages=pages(decisions,4);
  const slides:Slide[]=taskPages.map((_,page)=>({kind:'tasks' as const,title:'كل المهام المفتوحة',page,total:taskPages.length}));
  const current=slides[index%slides.length];const slideCount=slides.length;
  const move=(delta:number)=>{setIndex(i=>(i+delta+slideCount)%slideCount);setElapsed(0);};
  useEffect(()=>{const timer=window.setInterval(()=>{setNow(Date.now());if(paused||document.hidden)return;if(elapsed+1>=seconds){setIndex(i=>(i+1)%slideCount);setElapsed(0);}else setElapsed(elapsed+1);},1000);return()=>window.clearInterval(timer);},[paused,seconds,slideCount,elapsed]);
  useEffect(()=>{const handler=(event:KeyboardEvent)=>{if((event.target as HTMLElement).closest('button,select,input,a'))return;if(event.key===' '){event.preventDefault();setPaused(v=>!v);}if(event.key==='ArrowLeft'){setIndex(i=>(i+1)%slideCount);setElapsed(0);}if(event.key==='ArrowRight'){setIndex(i=>(i-1+slideCount)%slideCount);setElapsed(0);}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[slideCount]);
  const completed=tasks.filter(t=>t.status==='completed').length;const late=tasks.filter(t=>overdue(t,now));const progress=tasks.length?Math.round(completed/tasks.length*100):0;
  const stale=!preview&&(!lastUpdated||now-lastUpdated>65000);
  const comments=[...data.comments].filter(c=>tasks.some(t=>t.id===c.taskId)).sort((a,b)=>b.createdAt-a.createdAt);
  const spotlight=sorted.find(t=>t.status!=='completed');
  const fullScreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setNotice('تعذر ملء الشاشة. استخدم خيار ملء الشاشة في المتصفح.');}};
  const date=(time:number)=>new Intl.DateTimeFormat('ar-JO',{timeZone:'Asia/Amman',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(time);
  const displayedTasks=taskPages[current.page]||[];
  return <main className={`tv-shell tv-circle-mode${reduced?' tv-reduced':''}`} dir="rtl">
    <header className="tv-header"><div className="tv-brand"><img className="tv-official-logo" src="/titanium-logo.png" alt="شعار صيدليات تيتانيوم" width={78} height={78}/><div><b>TITANIUM</b><h1>غرفة متابعة الأعمال</h1></div></div><div className={`tv-connection ${stale?'stale':''}`} role="status"><span/>{preview?'معاينة التصميم · بيانات توضيحية':stale?'التحديث متوقف · آخر بيانات محفوظة':'متصل · تحديث تلقائي'}</div><div className="tv-clock"><strong>{new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Amman',hour:'2-digit',minute:'2-digit'}).format(now)}</strong><span>{new Intl.DateTimeFormat('ar-JO',{timeZone:'Asia/Amman',weekday:'long',day:'numeric',month:'long'}).format(now)} · عمّان</span></div></header>
    <section className="tv-stats" aria-label="مؤشرات العمل">
      {[{label:'المشاريع',value:projects.length,icon:FolderKanban,tone:'neutral',sub:'ضمن صلاحيات الحساب'},{label:'إجمالي المهام',value:tasks.length,icon:LayoutDashboard,tone:'neutral',sub:`${tasks.filter(t=>t.status==='progress').length} قيد التنفيذ`},{label:'بانتظار القرار',value:decisions.length,icon:Clock3,tone:'amber',sub:'طلبات ومهام للمراجعة'},{label:'المهام المتأخرة',value:late.length,icon:Flag,tone:'red',sub:'تحتاج متابعة'},{label:'الإنجاز المعتمد',value:`${progress}%`,icon:CheckCheck,tone:'green',sub:`${completed} من ${tasks.length} مهمة`}].map(s=><article className={`tv-stat ${s.tone}`} key={s.label}><div><s.icon/><span>{s.label}</span></div><strong key={String(s.value)}>{s.value}</strong><small>{s.sub}</small></article>)}
    </section>
    <div className="tv-section-heading"><div><span className="tv-eyebrow">متابعة تيتانيوم</span><h2>{current.title}</h2></div><div className="tv-section-meta"><span>{current.page+1} / {current.total}</span><span className="tv-line"/> {paused?'العرض متوقف مؤقتًا':`العرض التالي بعد ${seconds-elapsed} ث`}</div></div>
    <div className="tv-stage" key={`${current.kind}-${current.page}`}>
    {current.kind==='overview'&&<div className="tv-overview"><section className="tv-project-grid">{(projectPages[current.page]||[]).map((p,i)=>{const list=tasks.filter(t=>t.projectId===p.id);const done=list.filter(t=>t.status==='completed').length;const pct=list.length?Math.round(done/list.length*100):0;const blocked=list.filter(t=>t.blocker).length;return <article className="tv-project" key={p.id} style={{animationDelay:`${i*70}ms`}}><div className="tv-card-heading"><span className="tv-project-number">{String(current.page*4+i+1).padStart(2,'0')}</span><span>{p.status==='pending'?'بانتظار الموافقة':'مشروع نشط'}</span><ArrowUpLeft/></div><h3>{p.name}</h3><div className="tv-project-progress"><Ring value={pct}/><div><b>{done}<span> / {list.length}</span></b><p>مهام معتمدة</p></div></div><div className="tv-segment-bar">{['completed','progress','approval','open'].map(status=><span className={status} key={status} style={{width:`${list.length?list.filter(t=>t.status===status).length/list.length*100:0}%`}}/>)}</div><div className="tv-project-bottom"><span><i className="tv-dot blue"/>{list.filter(t=>t.status==='progress').length} قيد العمل</span><span className={blocked||list.some(t=>overdue(t,now))?'tv-red':''}>{blocked?`${blocked} متوقفة`:`${list.filter(t=>overdue(t,now)).length} متأخرة`}</span></div></article>;})}{!projects.length&&<Empty text="لا توجد مشاريع متاحة لهذا الحساب"/>}</section><aside className="tv-focus"><span className="tv-eyebrow"><Flag size={16}/> تحت المتابعة</span>{spotlight?<><Badge task={spotlight} now={now}/><h3>{spotlight.title}</h3><p>{spotlight.blocker||spotlight.details||'بانتظار تحديث من المسؤول'}</p><div className="tv-focus-owner"><span className="tv-avatar">{(spotlight.owner||spotlight.suggestedOwner||'؟').slice(0,1)}</span><div><b>{spotlight.owner||spotlight.suggestedOwner||'لم يحدد المسؤول'}</b><small>{data.projects.find(p=>p.id===spotlight.projectId)?.name}</small></div></div>{spotlight.dueDate&&<span className="tv-due"><Clock3 size={16}/> الموعد: {spotlight.dueDate}</span>}</>:<Empty text="لا توجد مهام مفتوحة حاليًا"/>}<div className="tv-focus-footer"><Activity size={17}/><span>الحالة من سجل منصة الإدارة</span></div></aside></div>}
    {current.kind==='tasks'&&<section className="tv-circles" aria-label="كل المهام غير المكتملة">{displayedTasks.map((t,i)=><div className="tv-circle-item" data-owner={t.owner||t.suggestedOwner||""} key={t.id}><h4 className="tv-circle-project">{data.projects.find(p=>p.id===t.projectId)?.name}</h4><article data-owner={t.owner||t.suggestedOwner||""} className={`tv-task-circle priority-${t.priority}${overdueDays(t,now)>0?' tv-overdue-circle':''}`} style={{animationDelay:`${i*35}ms`}}><h3>{t.title}</h3><span className="tv-circle-owner" data-owner={t.owner||t.suggestedOwner||""}>{t.owner||t.suggestedOwner||"غير مسندة"}</span><Badge task={t} now={now}/>{t.dueDate&&<time dateTime={t.dueDate}>موعد الإنجاز: {new Intl.DateTimeFormat("ar-SA",{calendar:"gregory",numberingSystem:"latn",day:"numeric",month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(t.dueDate+"T00:00:00Z"))}</time>}</article></div>)}{!displayedTasks.length&&<Empty text="لا توجد مهام مفتوحة حاليًا"/>}</section>}
    {current.kind==='team'&&<section className="tv-team-grid">{(teamPages[current.page]||[]).map(u=>{const assigned=tasks.filter(t=>t.owner===u.name||(!t.owner&&t.suggestedOwner===u.name));const done=assigned.filter(t=>t.status==='completed').length;const comment=comments.find(c=>c.author===u.name);return <article className="tv-team-card" key={u.id}><div className="tv-team-heading"><span className="tv-avatar large">{u.name.slice(0,1)}</span><div><h3>{u.name}</h3><span>{assigned.length} مهمة مسندة أو مقترحة</span></div><Ring value={assigned.length?Math.round(done/assigned.length*100):0} size={70}/></div><div className="tv-team-numbers"><div><b>{assigned.filter(t=>t.status==='progress').length}</b><span>قيد التنفيذ</span></div><div><b className="tv-red">{assigned.filter(t=>overdue(t,now)).length}</b><span>متأخرة</span></div><div><b className="tv-green">{done}</b><span>معتمدة</span></div></div><div className="tv-team-update"><span>آخر تعليق متاح</span><p>{comment?.body||'لا يوجد تحديث مسجل بعد'}</p>{comment&&<small>{date(comment.createdAt)}</small>}</div></article>;})}{!data.users.some(u=>u.active)&&<Empty text="لا يوجد أعضاء متاحون للعرض"/>}</section>}
    {current.kind==='decisions'&&<div className="tv-decisions"><section className="tv-decision-list">{(decisionPages[current.page]||[]).map(d=><article key={d.id}><span className="tv-decision-icon"><Clock3/></span><div><span className="tv-eyebrow">{d.label}</span><h3>{d.title}</h3><p>{d.person} · بانتظار قرار الإدارة</p></div><span className="tv-badge approval">معلّق</span></article>)}{!decisions.length&&<Empty text="لا توجد قرارات معلّقة حاليًا"/>}</section><aside className="tv-updates"><h3><Radio size={19}/> آخر التحديثات</h3>{comments.slice(0,3).map(c=><article key={c.id}><i/><div><b>{c.author}</b><p>{c.body}</p><small>{date(c.createdAt)}</small></div></article>)}{!comments.length&&<p className="tv-muted">لا توجد تعليقات مسجلة بعد</p>}{data.monitoring?.followups.slice(0,2).map(f=><article key={f.id}><i/><div><b>{followupLabels[f.kind]||'متابعة الفريق'}</b><small>{date(f.sentAt)}</small></div></article>)}</aside></div>}
    </div>
    <footer className="tv-footer"><div className="tv-controls"><Button onClick={()=>move(-1)} variant="ghost" size="icon" aria-label="العرض السابق"><ChevronRight/></Button><Button onClick={()=>setPaused(v=>!v)} variant="ghost" size="icon" aria-label={paused?'تشغيل العرض التلقائي':'إيقاف العرض التلقائي'}>{paused?<Play/>:<Pause/>}</Button><Button onClick={()=>move(1)} variant="ghost" size="icon" aria-label="العرض التالي"><ChevronLeft/></Button><label className="tv-speed"><span>الانتقال</span><select value={seconds} onChange={e=>{setSeconds(Number(e.target.value));setElapsed(0);}} aria-label="مدة كل عرض"><option value="15">15 ثانية</option><option value="20">20 ثانية</option><option value="30">30 ثانية</option><option value="45">45 ثانية</option></select></label></div><nav className="tv-view-nav" aria-label="صفحات المهام">{taskPages.map((_,page)=><Button key={page} variant="ghost" aria-label={`صفحة المهام ${page+1}`} aria-pressed={current.page===page} className={current.page===page?"active":""} onClick={()=>{setIndex(page);setElapsed(0);}}>{page+1}</Button>)}</nav><div className="tv-controls"><Button onClick={fullScreen} variant="ghost" size="icon" aria-label="ملء الشاشة"><Expand/></Button><Button onClick={onExit} variant="ghost" size="icon" aria-label="الخروج من وضع الشاشة"><X/></Button></div></footer>
    <div className="tv-bottom"><span>{notice|| (preview?'معاينة فقط · لا تمثل حالة العمل الحالية':lastUpdated?`آخر مزامنة ${date(lastUpdated)}`:'بانتظار أول مزامنة')}</span><span>العرض {index%slideCount+1} من {slideCount} · مساحة: تشغيل / إيقاف</span></div><div className="tv-timer"><span style={{width:`${elapsed/seconds*100}%`}}/></div>
  </main>;
}
